spring:
  application:
    name: authentication-application

  profiles:
    active: dev


  server:
    port: 8082

    #configuration

    #database configurations

    #email configurations

    #oauth2 configurations

